### ISSUE TITLE
metadata errors

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#17]
This latest error report from <https://github.com/NYU-CI/RCGraph> now tests all of the publications before exiting:

dataset `dataset-111` not found
```
{'title': 'Alternative employment strategies for hard-to-employ TANF recipients: final results from a test of transitional jobs and preemployment services in Philadelphia', 'datasets': ['dataset-103', 'dataset-111', 'dataset-112'], 'original': {'url': 'https://www.mdrc.org/sites/default/files/full_18.pdf', 'date_added': '2019-10-11 11:42:54'}}
```
from partition `publications/partitions/20190923_chapinhall_publications.json`

dataset `dataset-112` not found
```
{'title': 'Alternative employment strategies for hard-to-employ TANF recipients: final results from a test of transitional jobs and preemployment services in Philadelphia', 'datasets': ['dataset-103', 'dataset-111', 'dataset-112'], 'original': {'url': 'https://www.mdrc.org/sites/default/files/full_18.pdf', 'date_added': '2019-10-11 11:42:54'}}
```
from partition `publications/partitions/20190923_chapinhall_publications.json`

dataset `dataset-113` not found
```
{'title': 'The Effect of Work First Job Placements on the Distribution of Earnings: An Instrumental Variable Quantile Regression', 'datasets': ['dataset-076', 'dataset-113'], 'original': {'url': 'https://docplayer.net/62374992-The-effect-of-work-first-job-placements-on-the-distribution-of-earnings-an-instrumental-variable-quantile-regression-approach.html', 'date_added': '2019-10-11 11:42:54'}}
```
from partition `publications/partitions/20190923_chapinhall_publications.json`

dataset `dataset-114` not found
```
{'title': 'Welfare-to-work transition in the TANF era: Evidence from Mississippi', 'datasets': ['dataset-114', 'dataset-115', 'dataset-116', 'dataset-117', 'dataset-118', 'dataset-119'], 'original': {'url': 'https://pqdtopen.proquest.com/pubnum/3450368.html?FMT=AI', 'date_added': '2019-10-11 11:42:54'}}
```
from partition `publications/partitions/20190923_chapinhall_publications.json`

dataset `dataset-115` not found
```
{'title': 'Welfare-to-work transition in the TANF era: Evidence from Mississippi', 'datasets': ['dataset-114', 'dataset-115', 'dataset-116', 'dataset-117', 'dataset-118', 'dataset-119'], 'original': {'url': 'https://pqdtopen.proquest.com/pubnum/3450368.html?FMT=AI', 'date_added': '2019-10-11 11:42:54'}}
```
from partition `publications/partitions/20190923_chapinhall_publications.json`

**Comment by ceteri** [comment]
another one showed up from the BBK partition

dataset `dataset-434` not found
```
{'title': 'Shocks at large banks and banking sector distress: the Banking Granular Residual', 'datasets': ['dataset-434'], 'original': {'journal': 'BBk Discussion Paper', 'date_added': '2019-11-11 12:31:11'}}
```
from partition `publications/partitions/20190731_bundesbank_publications.json`

dataset `dataset-434` not found
```
{'title': 'What macroeconomic shocks affect the German banking system? Analysis in an integrated micro-macro model', 'datasets': ['dataset-013', 'dataset-434'], 'original': {'journal': 'BBk Discussion Paper', 'date_added': '2019-11-11 12:31:11'}}
```
from partition `publications/partitions/20190731_bundesbank_publications.json`

**Comment by srand525** [comment]
@ceteri `dataset-434` exists - was hanging in a PR from marcos but its merged now.
triaging

**Comment by ceteri** [comment]
Got it, thanks! That one (`dataset-434`) was fixed in the recent merge updates.

We've still got the 111-115 ones that are missing?

**Comment by srand525** [comment]
Datasets have been added back/corrected and partition updated. See latest merge in RCDatasets for details - closing issue here.

**Comment by ceteri** [comment]
Good, that resolves the errors from the current unit tests in `RCGraph`.

Note that by convention, generally the person who opens a GitHub issue should be the one who confirms a fix and closes the issue.
