### ISSUE TITLE
feedback: SDR

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#191]
We have our first official feedback from a domain expert who's reviewed results on https://rc.coleridgeinitiative.org/

Julia Lane, 2020-02-14:
https://docs.google.com/document/d/1x_1G_KNpPVbyNMfQp2v9E1UOborbTvO5WWmJSXuPfJg/edit

@ernestogimeno I'll assign this to you initially -- then can you please help create/assign the data drop issues among others on the team? 

This is a good first-test for federated queries :)

**Comment by ernestogimeno** [comment]
added #192

**Comment by ernestogimeno** [comment]
I found an abstract for an old publication that uses SDR. [This PDF](https://journals.sagepub.com/doi/pdf/10.1177/0162243988013001-212) is a collection of abstracts. This one along with Julia's mention of _"Some older papers using SED/SDR"_ I'm not sure if are captured in the datadrops I produced.

The publication I found is 
> "The Effect of Cohort on the Productivity of U.S.Physicists." Paula E.Stephan-GeorgiaStateUniversity-andSharon G.Levin-University of Missouri, St. Louis
