### ISSUE TITLE
metadata errors

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#21]
In the `20190731_bundesbank_publications.json` partition:

- title: `An analysis of the consistency of banksAo internal ratings` should be corrected to `An analysis of the consistency of banks' internal ratings` (see <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2905189>)
- title: `BanksAo Equity Stakes and Lending: Evidence from a Tax Reform` should be corrected to `Banks' equity stakes and lending: Evidence from a tax reform` (see <https://ideas.repec.org/p/zbw/bubdps/062018.html>)
- title: `Tax Status and Tax Response Heterogeneity of MultinationalsAo Dept Finance` duplicate of `Tax Status and Tax Response Heterogeneity of Multinationals' Debt Finance`
- title: `Tax vs. Regulation Policy and the Location of ,Financial Sector FDI*` should be corrected to `Tax vs. Regulation Policy and the Location of Financial Sector FDI` (see <https://ideas.repec.org/p/ces/ceswps/_5500.html>)
- title: `The Effects of MultinationalsAo Profit Shifting Activities on Real Investments` should be corrected to `The Effects of Multinationals' Profit Shifting Activities on Real Investments` (see <https://ideas.repec.org/a/ntj/journl/v62y2009i1p5-23.html>)
- title: `Why is the Response of MultinationalsAo Capital Structure Choice to Tax Incentives That Low? Some Possible Explanations` should be corrected to `Why is the Response of Multinationals' Capital-Structure Choice to Tax Incentives That Low? Some Possible Explanations` (see <https://ideas.repec.org/a/mhr/finarc/urnsici0015-2218(291106)672_123witrom_2.0.tx_2-4.html>)
- title: `YouAore banned! The effect of sanctions on German cross-border financial flows` should be corrected to `You're banned! the effect of sanctions on German cross-border financial flows` (see <https://ideas.repec.org/p/zbw/bubdps/122016.html>)

Julia needs a corpus update early the week of Dec 2 and these data quality issues are blockers.

**Comment by srand525** [comment]
see https://github.com/NYU-CI/RCPublications/blob/template_update/partitions/20190731_bundesbank_publications.json

There are duplicative titles across partitions. About a month ago I started to look at duplicates and wrote some code to deduplicate and combine the `original` subdicts so that we didn't lose metadata - at the time your instruction was that it was too early to be working on de-duplication - let me know if you want me to revisit and deal with duplicates across the partitions.

**Comment by ceteri** [comment]
The main problem is that the titles are incorrect. Downstream, title search is effectively broken due to the character encoding problems, so these publications won't go into the graph.

Duplicates aren't a big problem, that's simple to handle.

The problem with titles appears to be that character encoding isn't getting translated correctly. For example, `'` becomes `Ao` and that's probably due to a codec not used properly? That worries me, since we're taking input from Excel spreadsheets and other raw sources -- but then how much of the input so far has character encoding problems?

I've only checked two partitions so far, one from BBK and one from USDA.  This one from BBK has lots of errors, although the USDA one did not appear to.

**Comment by lobodemonte** [comment]
I'll be handling this issue

**Comment by lobodemonte** [comment]
In the bundesbank json I've found the following encoding issues: 
```
Ao--> '
Ai --> –
Au --> " 
```
But also for bundesbank, in german they sometimes do quotations like this: `„Gänsefüßchen“ `
with lower and higher double quotes, I'll treat the lower double quote as a regular \"

**Comment by ceteri** [comment]
These character encoding problems show up in titles for other partitions.

If it's simple to fix by:

  1. changing the characters manually in the source
  2. then adding a unit test to flag any that were missed

That's fine -- and actually better than regex or character substitution.

Ideally, using `unicodedata.normalize` to translate characters programmatically would be better -- as much possible.

**Comment by srand525** [comment]
I was looking into using `unicodedata.normalize` this morning, but couldn't identify a codec to resolve these particular issues. We discussed fixing these manually for the time being so that we are not blocking you while we try to figure out doing this programmatically

**Comment by lobodemonte** [comment]
A more complete set (what i see in the csv's and what I'll change it to) 
```
‚Äô --> '
‚Äò --> '
‚Äú --> "
‚Äù --> "
‚Äì --> -
```

**Comment by lobodemonte** [comment]
should we close this issue? I've removed and committed the affected files

**Comment by ceteri** [comment]
Sounds good to me.
