### ISSUE TITLE
Fix Title Errors in Publications

### ISSUE THREAD

**Issue by lobodemonte** [NYU-CI/RCPublications#286]
Title: No More Credit Score”: Employer Credit Check Bans and Signal Substitution
Issue: Missing Closing curly double quote
Files: 
./20191119_QuarterlyCensusofEmploymentandWages_publications.json
./20191119_QuarterlyWorkforceIndicators_publications.json

Title: A comparative analysis of the Early Childhood Environment Rating Scalea"Revised and Early Childhood Environment Rating Scale, Third Edition
Issue: Missing Closing curly double quote
Files:
./20191119_EarlyChildhoodLongitudinalProgram_publications.json

Title: D
Issue: Title Looks Wrong 
Files:
./20191119_NewYorkUnemploymentInsurance_publications.json

Title: Risk attitudes and the structure of decisionmaking: evidence from the Illinois hog industry
Issue: Missing Hyphen
Files:
./20200227_USDA_AgriculturalResourceManagementSurvey_part4_publications.json

**Comment by lobodemonte** [comment]
Title: The role of aerosol-radiation-cloud interactions in linking anthropogenic pollution over southern west Africa and dust emission over the Sahara
Issue: Wrong hyphens (actually EM-dashes I think)
Files: 
./20191223_dimensions_Global_Forecast_System_publications.json

**Comment by menoah** [comment]
- Addressed Errors in partitions

- For: 
Title: D
Issue: Title Looks Wrong
Files:
./20191119_NewYorkUnemploymentInsurance_publications.json

Updated Title to : 
Notable American   Women 1607–1950, Volume: Volume IV

Also cleaned up some formatting issues with this partition, which will be updated

**Comment by lobodemonte** [comment]
Thanks @menoah
