### ISSUE TITLE
Broken metadata

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#29]
A recent change in the format of the `journal` field in `original` -- which had been a string but is now a dictionary in some cases:
```
{'id': 'jour.1041807', 'title': 'Justice Quarterly'}
```

 - be mindful that changes in format have consequences in terms of troubleshooting and lost time elsewhere
 - if the `original` metadata doesn't stay consistent, we'll be forced to ignore it which is a big waste of labor and time

**Comment by srand525** [comment]
stuff like this is happening because our focus with linkages has been so far, on title and dataset primarily - we'll make sure to start checking for consistency in all fields now. One of us will go through and correct this instance and look for others.

**Comment by ceteri** [comment]
Right, that attention to detail must all change rapidly now, given the schedule for the next several months and the fact that we're integrating a much larger volume metadata from API calls plus more entities into the graph.

**Comment by srand525** [comment]
This particular error has been resolved if you want to close and @JasonZhangzy1757 is searching for and updating other instances.

**Comment by ceteri** [comment]
Thank you
