### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#3]
1. The `journal` and `publisher` fields are for the same entity -- or rather, we only need the `journal` field, much like in citations.
  2. `# of citations` -- nix it -- let's not have this at the top level, although it may be included within a dict from a specific API. In any case, it will change over time. Those kinds of metrics would be better to manage outside of the graph.
  3. `authors` -- best to keep these under the dict from the specific API where they came -- since they'll be so many variations, and must be resolved at a later stage.
  4. `funder` -- leave this out of the publications, and get more examples of it -- it can be added later, but there's a "0 or more" aspect to it, which may be better to model the way that we're going to handle `customer` entities.

Also, there should be notes about where to put the dict entries for APIs, such as:
```
"dimensions": {
  "foo": "bar",
  "citations": 5
},
"openaire": {
  "bar": "baz"
}
```

**Comment by srand525** [comment]
ok, lets discuss bc this gets into workflow. my thinking was that i was going to make a subdirectory of this repo where I work on enriching the kg with data from APIs. I wanted to have a simpler set of instructions just to get the linkages from the csvs that ben/marcos have been creating into json, then running the APIs on those partitions (stitched together?).
