### ISSUE TITLE
unicode handling

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#34]
This is not a blocker, but it needs to be fixed.

Before making any changes, **PLEASE** show where the source material is located, i.e., in which other repo, which file.  If you could please add that in the comments here it would be super helpful. Realistically, we lose info and means of troubleshooting root causes if that kind of link between errors (here) and source (there) aren't noted in the issue comments.

See
https://github.com/NYU-CI/RCPublications/blob/master/partitions/20191119_SurveyofEarnedDoctorates_publications.json

The following are titles with unicode characters that aren't getting translated correctly, and it's probably a codec issue:

- "University and Department Influences on ScientistsaTM Occupational Outcomes"
- "Academic Entrepreneurship: The Bayh-Dole Act versus the ProfessoraTMs Privilege"
- "A National Study of the Influence of the Community College Pathway on Female StudentsaTM STEM Baccalaureate Success"
- "EditorsaTM Notes" 
- "BPD Emerging Leaders 2010a\"2016: Identifying and Responding to the Need for New Academic Leadership"

**Comment by JasonZhangzy1757** [comment]
Yes, it is the same codec issue we ran into last time. I attached the correct translations and the source link below:
 
"Academic Entrepreneurship: The Bayh-Dole Act versus the Professor's Privilege"
https://github.com/NYU-CI/RichContextMetadata/blob/7b59109ba0bc495ea1c6070f58a2a4cbb682bc89/metadata/20191119_SurveyofDoctorateRecipients/SurveyofDoctorateRecipients_linkages.csv
 
"A National Study of the Influence of the Community College Pathway on Female Students' STEM Baccalaureate Success"
https://github.com/NYU-CI/RichContextMetadata/blob/05e8050fc595241b6ddf8519f340eb911aeab837/metadata/ncses/exports/Survey_of_Earned_Doctorates_linkages.csv
 
"University and Department Influences on Scientists' Occupational Outcomes"
"Editors' Notes"
 "BPD Emerging Leaders 2010 - 2016: Identifying and Responding to the Need for New Academic Leadership"
https://github.com/NYU-CI/RichContextMetadata/blob/master/metadata/20191119_SurveyofEarnedDoctorates/SurveyofEarnedDoctorates_linkages.csv


and I'll now go ahead and update the partitions.

**Comment by ceteri** [comment]
Here's a programmatic way to handle unicode characters during CSV => JSON translation:
https://gist.github.com/ceteri/bdfb2be4b7ea169c2fc813ab80557623

**Comment by ceteri** [comment]
resolved with #37
