### ISSUE TITLE
A strange unicode error

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#41]
In the `20191119_NationalCenterforEducationStatisticsData_publications.json` partition, see the title `"Skunks in an English Woodland: Should England Embrace For\\Profit Higher Education?"`

The `\\` should be resolving as a `-` dash instead, and here's a URL for the article
<https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-923X.12689>

**Comment by lobodemonte** [comment]
I checked both the CSVs this came from and the JSON and my guess is that this issue was introduced somewhere along the validation of the entries in the CSV.
