### ISSUE TITLE
title error?

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#54]
In the `20191231_noaa_manual_sbr.json` partition, this title is probably an error :)

 - `https://coast.noaa.gov/data/digitalcoast/pdf/econ-report.pdf`

Also, need to add a unit test such that if a title parses correctly as a URL, then fail.

**Comment by srand525** [comment]
resolved by #55

**Comment by ceteri** [comment]
No, this is not resolved by the PR -- since there is no updates to the unit tests to avoid this case in the future.

**Comment by srand525** [comment]
see now

**Comment by ceteri** [comment]
Thanks!
